### ISSUE TITLE
devel-0.6: BAD-WOLF during echo negociation

### ISSUE THREAD

**Issue by msune** [bisdn/rofl-core#44]
It is only reproducible with valgrind, which leads to think it is a race-condition or timing is involved. Can be reproduced with xdpd running under valgrind and against oftest1.2/roftest

I had to combine valgrind + gdb to get the trace (uncommented the `assert()` in `eBadVersion` )
```
root@debian7:/home/marc/xdpd/build/src/xdpd# gdb --args ./xdpd
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/marc/xdpd/build/src/xdpd/xdpd...done.
(gdb)  target remote | /usr/lib/valgrind/../../bin/vgdb --pid=740
Remote debugging using | /usr/lib/valgrind/../../bin/vgdb --pid=740
relaying data between gdb and process 740
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
[Switching to Thread 740]
0x0000000004000af0 in ?? () from /lib64/ld-linux-x86-64.so.2
(gdb) r
The "remote" target does not support "run".  Try "help target" or "continue".
(gdb) c
Continuing.

Program received signal SIGABRT, Aborted.
0x0000000006341165 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x0000000006341165 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00000000063443e0 in *__GI_abort () at abort.c:92
#2  0x000000000633a311 in *__GI___assert_fail (assertion=0x56caddc "0 == 1", file=<optimized out>, line=80, 
    function=0x56cb280 "rofl::eBadVersion::eBadVersion(const string&)") at assert.c:81
#3  0x0000000005532a31 in rofl::eBadVersion::eBadVersion (this=0x25b58540, __arg=...) at /home/marc/rofl-core/build/../src/rofl/common/croflexception.h:80
#4  0x0000000005643ee4 in rofl::openflow::cofmsg_error::set_err_type (this=0x25058960, type=1)
    at ../../../../../../src/rofl/common/openflow/messages/cofmsg_error.cc:239
#5  0x00000000056430d7 in rofl::openflow::cofmsg_error::cofmsg_error (this=0x25058960, of_version=0 '\000', xid=474150065, err_type=1, err_code=0, 
    data=0x25b57d10 "\003\002", datalen=8) at ../../../../../../src/rofl/common/openflow/messages/cofmsg_error.cc:40
#6  0x000000000555ad7f in rofl::openflow::cofmsg_error_bad_request_bad_version::cofmsg_error_bad_request_bad_version (this=0x25058960, ofp_version=0 '\000', 
    xid=474150065, data=0x25b57d10 "\003\002", datalen=8) at /home/marc/rofl-core/build/../src/rofl/common/openflow/messages/cofmsg_error.h:535
#7  0x00000000055a59dc in rofl::crofconn::echo_request_rcvd (this=0x25b23c30, msg=0x250584f0) at ../../../../src/rofl/common/crofconn.cc:1028
#8  0x00000000055a47c3 in rofl::crofconn::handle_messages (this=0x25b23c30) at ../../../../src/rofl/common/crofconn.cc:824
#9  0x00000000055aab54 in rofl::crofconn::handle_event (this=0x25b23c30, ev=...) at ../../../../src/rofl/common/crofconn.h:441
#10 0x000000000551168f in rofl::ciosrv::__handle_event (this=0x25b23c38) at ../../../../src/rofl/common/ciosrv.cc:78
#11 0x00000000055126f2 in rofl::cioloop::run_on_events (this=0x25b1e5d0) at ../../../../src/rofl/common/ciosrv.cc:257
#12 0x0000000005511954 in rofl::cioloop::run_loop (this=0x25b1e5d0) at ../../../../src/rofl/common/ciosrv.cc:149
#13 0x00000000004b5618 in rofl::cioloop::run (this=0x25b1e5d0) at /usr/local/include/rofl/common/ciosrv.h:231
#14 0x00000000004b31e4 in xdpd::system_manager::init (argc=4, argv=0x7ff000608) at ../../../../src/xdpd/management/system_manager.cc:245
#15 0x00000000004a2166 in main (argc=4, argv=0x7ff000608) at ../../../src/xdpd/xdpd.cc:25
(gdb) 

```

**Comment by msune** [comment]
Nedless to say echo req. had the right version (0x3), since it works without debug.
